image:
  file: .gitpod.Dockerfile

tasks:
  - init: docker-compose up -d
    command: docker-compose logs -f

ports:
  - port: 9200
    onOpen: open-preview
  - port: 5601
    onOpen: open-preview
  - port: 5044
    onOpen: ignore
